### ISSUE TITLE
Support a mode setting that swaps APNS URLs

### ISSUE THREAD

**Issue by lserman** [jrbeck/mercurius#6]
Currently have to do something like this

```
APNS.host =
  case Rails.env
  when 'production'
    'gateway.push.apple.com'
  else
    'gateway.sandbox.push.apple.com'
  end
```

Would be nice if we could do

```
APNS.mode = :production
# or
APNS.mode = :development
```

**Comment by jrbeck** [comment]
Good idea. You can use the following

    case Rails.env
    when 'production'
      APNS.set_mode(:develop)
    else
      APNS.set_mode(:production)
    end
